admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8001

dynamic_resources:
  lds_config:
    api_config_source:
      api_type: REST
      refresh_delay: 5s
      cluster_names: [xds_cluster]
  cds_config:
    api_config_source:
      api_type: REST
      refresh_delay: 5s
      cluster_names: [xds_cluster]

node:
  cluster: edge
  id: default
  locality:
    zone: zone-default-zone
    region: default-region

static_resources:
  listeners:
    - name: edge
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 10808
      filter_chains:
        - filters:
          - name: envoy.http_connection_manager
            config:
              forward_client_cert_details: sanitize_set
              set_current_client_cert_details:
                  uri: true
              codec_type: AUTO
              access_log:
                - name: envoy.file_access_log
                  config:
                    path: "/dev/stdout"
              stat_prefix: ingress
              route_config:
                name: edge-routes
                virtual_hosts:
                  - name: tools
                    domains: ["*"]
                    routes:
                      - match:
                          prefix: "/control-api/"
                        route:
                          prefix_rewrite: "/"
                          cluster: control-api
                      - match:
                          prefix: "/control-api"
                        route:
                          prefix_rewrite: "/"
                          cluster: control-api
              http_filters:
                - name: gm.metrics
                  typed_config:
                    "@type": type.googleapis.com/deciphernow.gm_proxy.filters.MetricsConfig
                    metrics_port: 8080
                    metrics_host: 0.0.0.0
                    metrics_dashboard_uri_path: /metrics
                    metrics_prometheus_uri_path: /prometheus
                    prometheus_system_metrics_interval_seconds: 15
                    metrics_ring_buffer_size: 4096
                    metrics_key_function: depth
                    metrics_key_depth: "2"
                - name: envoy.router
  clusters:
    - name: xds_cluster
      connect_timeout: 0.25s
      type: STRICT_DNS
      lb_policy: ROUND_ROBIN
      load_assignment:
        cluster_name: xds_cluster
        endpoints:
        - lb_endpoints:
          - endpoint:
              address:
                socket_address:
                  address: control.fabric.greymatter.dev
                  port_value: 50001
    - name: control-api
      connect_timeout: 5s
      type: LOGICAL_DNS
      lb_policy: ROUND_ROBIN
      load_assignment:
        cluster_name: control-api
        endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: control-api.fabric.greymatter.dev
                    port_value: 5555
      transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
          common_tls_context:
            tls_certificates:
              certificate_chain:
                filename: /app/certificates/server.crt
              private_key:
                filename: /app/certificates/server.key
            validation_context:
              trusted_ca:
                filename: /app/certificates/ca.crt